services:
  postgres:
    image: postgres:16-alpine
    container_name: task_db
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d
    networks:
      - task-network

  backend:
    build: ./backend
    container_name: task_backend
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_NAME}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY: ${JWT_SECRET_KEY}
      EXPIRATION_TOKEN: ${JWT_EXPIRATION}
    depends_on:
      - postgres
    networks:
      - task-network

  frontend:
    build: ./frontend
    container_name: task_frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    networks:
      - task-network

volumes:
  postgres_data:

networks:
  task-network:
    driver: bridge